EPAM_TICKETO_TASK/EpamTicketoTask.EmptyTemplate/Models/ViewModels/Event/EventDetailViewModel.cs
using EpamTicketoTask.EmptyTemplate.Models.ViewModels.Ticket;
using Microsoft.AspNetCore.Html;
using System;
using System.Collections.Generic;

namespace EpamTicketoTask.EmptyTemplate.Models.ViewModels.Event
{
    public class EventDetailViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public DateTime Date { get; set; }
        public string VenueFull { get; set; }
        public string Photo { get; set; }
        public HtmlString Description { get; set; }

        public IEnumerable<TicketIndexViewModel> Tickets { get; set; }
    }
}

EPAM_TICKETO_TASK/EpamTicketoTask.EmptyTemplate/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using System.Globalization;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using EpamTicketoTask.BusinessLogic.Abstractions;
using EpamTicketoTask.BusinessLogic.Models.DTO;
using AutoMapper;
using EpamTicketoTask.BusinessLogic.Infrastucture;
using EpamTicketoTask.EmptyTemplate.Models.ViewModels.Auth;

namespace EpamTicketoTask.EmptyTemplate.Controllers
{
    public class AuthController : Controller
    {
        private IHostingEnvironment environment;
        private IServiceStorage serviceStorage;
        public AuthController(IServiceStorage serviceStorage, IHostingEnvironment environment)
        {
            this.environment = environment;
            this.serviceStorage = serviceStorage;
        }


        [HttpGet]
        public IActionResult Registration()
        {
            return View(new RegistrationViewModel());
        }
        [HttpPost]
        public IActionResult Registration(RegistrationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            UserDTO user = new UserDTO
            {
                UserName = model.UserName,
                Password = model.Password,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Localization = new CultureInfo(model.Localization)
            };
            try
            {
                serviceStorage.GetService<IUserService>().Make(user);
            }
            catch (ValidationException e)
            {
                ModelState.AddModelError(e.Property, e.Message);
                return View(model);
            }
            serviceStorage.GetService<IUserService>().SignIn(model.UserName, model.Password, false);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Login([FromQuery] string returnUrl = "~/Home/Index")
        {
            return View(new LoginViewModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        public IActionResult Login(LoginViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                serviceStorage.GetService<IUserService>().SignIn(model.Username, model.Password, model.RememberMe);
            }
            catch (ValidationException e)
            {
                ModelState.AddModelError(e.Property, e.Message);
                return View(model);
            }
            return Redirect(model.ReturnUrl);
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]//Finally it works
        public IActionResult Profile(string userName)
        {
            UserDTO user;
            if (userName == null)
                user = serviceStorage.GetService<IUserService>().GetByName(User.Identity.Name);
            else
                user = serviceStorage.GetService<IUserService>().GetByName(userName);

            Mapper.Initialize(cfg => cfg.CreateMap<UserDTO, UserDisplayViewModel>());

            UserDisplayViewModel model = Mapper.Map<UserDTO, UserDisplayViewModel>(user);
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "admin, user")]//Finally it works
        [ActionName("ProfileEdit")]
        public IActionResult EditProfile()
        {
            UserDTO user = serviceStorage.GetService<IUserService>().GetByName(User.Identity.Name);
            UserEditViewModel userModel = new UserEditViewModel
            {
                FirstName = user.FirstName,
                LastName = user.LastName,
                Localization = user.Localization.TwoLetterISOLanguageName,
                Address = user.Address,
                Phone = user.PhoneNumber
            };
            return View(userModel);
        }

        [HttpPost]
        [Authorize(Roles = "admin, user")]
        [ActionName("ProfileEdit")]
        public IActionResult EditProfile(UserEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            string photoPath;
            try
            {
                photoPath=ImageUploadAsync(model.Photo).Result;
            }
            catch (IOException)
            {
                ModelState.AddModelError("Photo","Error while loading photo, try again");
                return View(model);
            }

            serviceStorage.GetService<IUserService>().Update(new UserDTO
            {
                UserName = User.Identity.Name,
                Photo = photoPath.Equals(string.Empty) ? model.PhotoPath : photoPath,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Localization = new CultureInfo(model.Localization),
                Address = model.Address,
                PhoneNumber = model.Phone
            });
            return RedirectToAction("Profile");
        }


        [HttpGet]
        [Authorize(Roles = "admin")]
        [ActionName("AdminPanel")]
        public IActionResult AdminPanel()
        {
            var usersDto = serviceStorage.GetService<IUserService>().GetAll().Where(u => u.UserName != User.Identity.Name);
            var rolesDto = serviceStorage.GetService<IRoleService>().GetAll();
            var roles = rolesDto.Select(r => r.Name);
            IEnumerable<UserRoleUpdateViewModel> users = usersDto.Select(
                 u => new UserRoleUpdateViewModel()
                 {
                     UserName = u.UserName,
                     FirstName = u.FirstName,
                     LastName = u.LastName,
                     Photo = u.Photo,
                     AllRoles = roles
                     //ОООчень стыдно за такой запрос но нв другое нет времени
                     //RolesToAssign = await userManager.GetRolesAsync(u)
                     //не стыдно, я уже и не помню что тут было

                 }).ToList();

            foreach (var u in users)
            {
                u.RolesToAssign = serviceStorage
                    .GetService<IUserService>()
                    .GetRoles(u.UserName);
            }
            AdminPanelViewModel model = new AdminPanelViewModel
            {
                UserList = users
            };
            return View(model);
        }


        [HttpPost]
        [ActionName("RoleCheckerPartial")]
        public IActionResult RoleCheckerPartial(UserRoleUpdateViewModel model, string returnUrl)
        {
            serviceStorage.GetService<IUserService>().AssignRolesAsync(model.UserName, model.RolesToAssign).Wait();

            return LocalRedirect(returnUrl);
        }
        [Authorize]
        public IActionResult LogOut()
        {
            serviceStorage.GetService<IUserService>().SignOut();
            return RedirectToAction("Index", "Home");
        }

        private async Task<string> ImageUploadAsync(IFormFile file)
        {
            if (file == null)
            {
                return string.Empty;
            }
            string fileName = string.Concat(DateTime.Now.ToString("yyyy-MM-dd HHmmttss"), file.FileName);
            try
            {
                using (var fileStream = new FileStream(Path.Combine(environment.WebRootPath, "images", "Users", fileName), FileMode.CreateNew))
                {
                    await file.CopyToAsync(fileStream);
                }
            }
            catch (IOException e)
            {
              throw e;
            }
            return fileName;
        }
    }
}

EPAM_TICKETO_TASK/EpamTicketoTask.EmptyTemplate/Controllers/EventController.cs
using EpamTicketoTask.BusinessLogic.Abstractions;
using EpamTicketoTask.BusinessLogic.Infrastucture;
using EpamTicketoTask.BusinessLogic.Models.DTO;
using EpamTicketoTask.EmptyTemplate.Models.ViewModels.Event;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace EpamTicketoTask.EmptyTemplate.Controllers
{
    public class EventController : Controller
    {
        private IHostingEnvironment environment;
        private IServiceStorage serviceStorage;

        public EventController(IHostingEnvironment environment, IServiceStorage serviceStorage)
        {
            this.environment = environment;
            this.serviceStorage = serviceStorage;
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            EventEditViewModel model = new EventEditViewModel()
            {
                VenueList = GetVenuesList()
            };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Create(EventEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.VenueList = GetVenuesList();
                return View(model);
            }

            string photoPath;
            try
            {
                photoPath = ImageUploadAsync(model.Photo).Result;
            }
            catch (IOException)
            {
                ModelState.AddModelError("Photo", "Error while loading photo, try again");
                return View(model);
            }
            serviceStorage.GetService<IEventService>().Make(new EventDTO
            {
                Name = model.Name,
                Photo = photoPath,
                VenueId = model.VenueId,
                Date = model.Date,
                Description = model.Description,
            });
            return Redirect("~/Home/Index");

        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Edit(string eventId)
        {
            EventDTO dtoModel = serviceStorage.GetService<IEventService>().Get(eventId);

            EventEditViewModel model = new EventEditViewModel()
            {
                Id = dtoModel.Id,
                Name = dtoModel.Name,
                VenueId = dtoModel.VenueId,
                Date = dtoModel.Date,
                Description = dtoModel.Description,
                VenueList = GetVenuesList(),
                OldPhoto = dtoModel.Photo
            };
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public IActionResult Edit(EventEditViewModel model)
        {

            if (!ModelState.IsValid)
            {
                model.VenueList = GetVenuesList();
                return View(model);
            }
            string photoPath;
            try
            {
                photoPath = ImageUploadAsync(model.Photo).Result;
            }
            catch (IOException)
            {
                ModelState.AddModelError("Photo", "Error while loading photo, try again");
                return View(model);
            }
            serviceStorage.GetService<IEventService>().Update(new EventDTO
            {
                Id = model.Id,
                Name = model.Name,
                Photo = (photoPath == string.Empty) ? model.OldPhoto : photoPath,
                VenueId = model.VenueId,
                Date = model.Date,
                Description = model.Description
            });
            list = null;
            return Redirect("~/Home/Index");

        }


        [HttpGet]
        [Authorize(Roles = "admin")]
        public IActionResult Delete(string eventId)
        {
            EventDTO dtoModel = serviceStorage.GetService<IEventService>().Get(eventId);
            EventDisplayViewModel model = new EventDisplayViewModel
            {
                Date = dtoModel.Date,
                Id = dtoModel.Id,
                Name = dtoModel.Name,
                Photo = dtoModel.Photo,
                VenueFull = $"{dtoModel.CityName}, {dtoModel.Address}"
            };
            return View(model);
        }
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ActionName("Delete")]
        public IActionResult DeleteConfirm(EventDisplayViewModel model)
        {
            try
            {
                serviceStorage.GetService<IEventService>().Delete(model.Id);
            }
            catch (ValidationException e)
            {
                ModelState.AddModelError("ConEv", e.Message);
                return View(model);
            }
            return Redirect("~/Home/Index");
        }

        private async Task<string> ImageUploadAsync(IFormFile file)
        {
            if (file == null)
            {
                return string.Empty;
            }
            string fileName = string.Concat(DateTime.Now.ToString("yyyy-MM-dd HHmmtt"), file.FileName);
            try
            {
                using (var fileStream = new FileStream(Path.Combine(environment.WebRootPath, "images", "Events", fileName), FileMode.CreateNew))
                {
                    await file.CopyToAsync(fileStream);
                }
            }
            catch (IOException)
            {
                //IMPOSSSIBRU!!!!!
                throw new NotImplementedException("IMPOSSSIBLE!!!");
            }
            return fileName;
        }


        private IEnumerable<SelectListItem> list;
        private IEnumerable<SelectListItem> GetVenuesList()
        {
            if (list == null)
            {
                list = serviceStorage.GetService<IVenueService>().GetAll()
                    .Select(v => new SelectListItem
                    {
                        Value = v.Id,
                        Text =$"{v.Name} - {v.CityName}, {v.Address}"
                    });
            }
            return list;
        }
    }
}

EPAM_TICKETO_TASK/EpamTicketoTask.EmptyTemplate/Views/Home/EventDetail.cshtml
@model EpamTicketoTask.EmptyTemplate.Models.ViewModels.Event.EventDetailViewModel
@{
    ViewData["Title"] = Model.Name + " - Tickets";
}
<div class="card event-detail">
    <div class="card-head">
        <div class="event-banner">
            @if (@Model.Photo != string.Empty)
            {<img src="~/images/Events/@Model.Photo" width="256" height="256" /> }
            else
            {<img src="~/images/no-banner.jpg" width="256" height="256" />}
        </div>
        <div class="event-data">
            <h2>@Localizer["place"]: @Model.VenueFull</h2>
            <h3>@Localizer["adress"]: @Model.VenueFull</h3>
            <h4>@Localizer["date"]: @Model.Date.</h4>
        </div>
    </div>
  
    <div class="clear"></div>
    <hr />
    <div class="card-info">
       
        <h2>@Localizer["description"]:</h2>

        <div>@(Model.Description)</div>

        @if (User.IsInRole("admin"))
            {
            <a class="flat-button red-hover" asp-action="Delete" asp-controller="Event" asp-route-eventId="@Model.Id">
                <i class="fa fa-remove" aria-hidden="true"></i>
                @Localizer["Delete"]
            </a>
            <a class="flat-button" asp-action="Edit" asp-controller="Event" asp-route-eventId="@Model.Id">
                <i class="fa fa-edit"></i>
                @Localizer["Edit"]
            </a>
                <div class="clear"></div>
        }
    </div>
</div>
<h1>@Localizer["thereis"] @Model.Tickets.Count() @Localizer["ticketsTo"] @Model.Name:</h1>
<hr />
<div class="card-list">
    @if (User.Identity.IsAuthenticated)
    {
        <a href="~/Ticket/Add?eventId=@Model.Id&eventName=@Model.Name">
            <div class="card ticket-card card-selectable card-tall">
                <div class="card-add-template">
                    <div>
                        <i class="fa fa-plus-circle"></i>
                        <span class="hint">@Localizer["Add"]</span>
                    </div>
                </div>
            </div>
        </a>
    }
    @foreach (var Ticket in this.Model.Tickets)
    {
        @if (!Ticket.IsSold)
        {
            <div class="card ticket-card card-small">
                <div class="card-head">
                    <h1>@Ticket.EventName </h1>
                </div>
                <hr />
                <div class="card-info">
                    <p>
                        <a asp-controller="Auth" asp-action="Profile" asp-route-userName="@Ticket.SellerUserName">
                            <i class="fa fa-fw fa-user"></i> @Localizer["seller"]: @Ticket.SellerFullName
                        </a>
                    </p>
                    <p>
                        <i class="fa fa-fw fa-bitcoin"></i> @Localizer["price"]: @Ticket.Price BYN
                    </p>
                    @if (!Ticket.IsSold)
                    {
                        <p>
                            <i class="fa fa-fw fa-circle-o" aria-hidden="true"></i> @Localizer["orders"]: @Ticket.OrderCount
                        </p>
                    }
                    else
                    {
                        <p>
                            <i class="fa fa-fw fa-check-circle-o" aria-hidden="true"></i> @Localizer["sold"]
                        </p>
                    }
                    <p class="card-expand-head">
                        <i class="fa fa-fw fa-chevron-down" aria-hidden="true"></i> @Localizer["Notes"]:
                    </p>
                    <div class="card-expand">
                        @if (Ticket.Notes == null)
                        {@Localizer["NoNotes"]}
                        else
                        {@Ticket.Notes}
                    </div>
                    @if (Ticket.SellerUserName == User.Identity.Name)
                    {
                        <a class="flat-button wide">@Localizer["youticket"]</a>
                    }
                    else
                    {
                        <a href="~/Order/Add?ticketId=@Ticket.Id" class="flat-button wide">@Localizer["ordernow"]</a>
                    }
                </div>
                <div>
                </div>
            </div>
        }
    }
    <hr />
</div>
@section ContentTitle{
    <div class="title"><h1>@Model.Name</h1></div>
}

EPAM_TICKETO_TASK/EpamTicketoTask.EmptyTemplate/Views/Home/Index.cshtml
@model IEnumerable<EpamTicketoTask.EmptyTemplate.Models.ViewModels.Event.EventDisplayViewModel>
@{
    ViewData["Title"] = "Ticketo - You Ticket Re-Saling Platform";
}

<div class="card-list">
    @if (User.IsInRole("admin"))
    {
        <a asp-action="Create" asp-controller="Event">
            <div class="card event-card card-selectable">
                <div class="card-add-template">
                    <div>
                        <i class="fa fa-plus-circle"></i>
                        <span class="hint">@Localizer["Add"]</span>
                    </div>
                </div>
            </div>
        </a>
    }
    @foreach (var Event in this.Model)
    {

        <div class="card event-card card-selectable">
            <a href="~/Home/EventDetail?eventId=@Event.Id">
                <div class="card-head">
                    @if (@Event.Photo!=string.Empty)
                    { <img src="~/images/Events/@Event.Photo" /> }
                    else
                    { <img src="~/images/no-banner.jpg" /> }
                </div>       
                <div class="card-info">
                    <h1>@Event.Name</h1>
                    <hr />
                    <p><i class="fa fa-fw fa-map-marker"></i> @Event.VenueFull</p>
                    <p><i class="fa fa-fw fa-calendar"></i> @Event.Date</p>
                </div>
            </a>
            @if (User.IsInRole("admin"))
            {
                <div class="edit-buttons">
                    <a class="red-hover" asp-action="Delete" asp-controller="Event" asp-route-eventId="@Event.Id">
                    <i class="fa fa-remove" aria-hidden="true"></i>
                       @Localizer["Delete"]
                    </a>
                    <a asp-action="Edit" asp-controller="Event" asp-route-eventId="@Event.Id">
                    <i class="fa fa-edit"></i>
                        @Localizer["Edit"]
                    </a>
                </div>
                <div class="clear"></div>
            }
        </div>


    }

</div>
@section ContentTitle{
    <div class="title">
        <h1>
            @Localizer["Events"]
        </h1>
    </div>
}

EPAM_TICKETO_TASK/EpamTicketoTask.EmptyTemplate/Views/Home/MyOrders.cshtml
@model IEnumerable<EpamTicketoTask.EmptyTemplate.Models.ViewModels.Order.OrderIndexViewModel>
@{
    ViewData["Title"] = "Ticketo - You Ticket Re-Saling Platform";
}

<div class="card-list">
    @foreach (var Order in this.Model)
    {

        <div class="card ticket-card card-small">
            <div class="card-head">
                <h1>@Order.TicketEventName</h1>
            </div>
            <hr />
            <div class="card-info">

                <p>
                    <i class="fa fa-fw fa-user"></i> @Localizer["seller"]: @Order.SellerFullName
                </p>
                <p>
                    <i class="fa fa-fw fa-bitcoin"></i> @Localizer["price"]: @Order.TicketPrice
                </p>
                <p class="card-expand-head">
                    <i class="fa fa-fw fa-chevron-down" aria-hidden="true"></i> @Localizer["Notes"]:
                </p>
                <div class="card-expand">
                    @if (Order.TicketNotes == null)
                    {@Localizer["NoNotes"]}
                    else
                    {@Order.TicketNotes}
                </div>
                <a href="~/Home/EventDetail?eventId=@Order.TicketEventId" class="flat-button wide">@Localizer["EvInfo"]</a>





                @if (Order.Status == EpamTicketoTask.Data.Models.OrderStatuses.Rejected)
                {
                    <p><i class="fa fa-fw fa-cogs"></i> @Localizer["status"]: <b class="red">@Localizer[Order.Status.ToString()]</b></p>

                    <p class="card-expand-head">
                        <i class="fa fa-fw fa-chevron-down" aria-hidden="true"></i> @Localizer["Reason"]:
                    </p>
                    <div class="card-expand">
                        @if (Order.Comment == null)
                        {@Localizer["NoReason"]}
                        else
                        {@Order.Comment}
                    </div>
                }
                @if (Order.Status == EpamTicketoTask.Data.Models.OrderStatuses.Confirmed)
                {
                    <p><i class="fa fa-fw fa-cogs"></i> @Localizer["status"]: <b class="green">@Localizer[Order.Status.ToString()]</b></p>

                    <p>
                        <i class="fa fa-fw fa-check-square-o"></i> @Localizer["TrackNO"]:<a target="_blank" href="https://track24.ru/?code=@Order.TrackNo">@Order.TrackNo</a>
                    </p>
                }
                @if (Order.Status == EpamTicketoTask.Data.Models.OrderStatuses.WaitingConfirmation)
                {
                    <p><i class="fa fa-fw fa-cogs"></i> @Localizer["status"]: <b>@Localizer[Order.Status.ToString()]</b></p>

                    <p>
                        <a asp-action="DeletePartial" asp-controller="Order" asp-route-orderId="@Order.Id" asp-route-eventName="@Order.TicketEventName" class="red-hover viewDialog">
                            <i class="fa fa-fw fa-close" aria-hidden="true"></i> @Localizer["RemoveOrder"]
                        </a>
                    </p>
                }


            </div>

        </div>
    }
</div>
<div id="dialog">
    <div class="content"></div>
</div>
@section ContentTitle{
    <div class="title"><h1>@Localizer["MyOrders"]</h1></div>
}

<script>
    $(document).ready(function () {

        $(".viewDialog").on("click", function (e) {
            e.preventDefault();
            $("#dialog").children()
                .load(this.href);
            $("#dialog")
                .show();
        });
    });
</script>

EPAM_TICKETO_TASK/EpamTicketoTask.EmptyTemplate/Views/Home/MyTickets.cshtml
@model IEnumerable<EpamTicketoTask.EmptyTemplate.Models.ViewModels.Ticket.TicketIndexViewModel>
@{
    ViewData["Title"] = "Ticketo - You Ticket Re-Saling Platform";
}

<div class="card-list">
    @foreach (var Ticket in this.Model)
    {
        <div class="card ticket-card card-small">
            <div class="card-head">
                <h1>@Ticket.EventName </h1>
            </div>
            <hr />
            <div class="card-info">
                <p>
                    <i class="fa fa-fw fa-bitcoin"></i> @Localizer["price"]: @Ticket.Price BYN
                </p>
                @if (!Ticket.IsSold)
                {
                    <p>
                        <i class="fa fa-fw fa-circle-o" aria-hidden="true"></i> @Localizer["orders"]: @Ticket.OrderCount
                    </p>
                }
                else
                {
                    <p class="green">
                        <i class="fa fa-fw fa-check-circle-o" aria-hidden="true"></i> @Localizer["SoldStatus"]
                    </p>
                }
                <p class="card-expand-head">
                    <i class="fa fa-fw fa-chevron-down" aria-hidden="true"></i> @Localizer["Notes"]:
                </p>
                <div class="card-expand">
                    @if (Ticket.Notes == null)
                    {@Localizer["NoNotes"]}
                    else
                    {@Ticket.Notes}
                </div>

                @if (!Ticket.IsSold && Ticket.OrderCount != 0)
                {
                    <a href="~/Order/Management?ticketId=@Ticket.Id" class="flat-button wide">@Localizer["ToOrders"]</a>
                }
                else
                {
                    <a href="~/Home/EventDetail?eventId=@Ticket.EventId" class="flat-button wide">@Localizer["EvInfo"]</a>
                }
            </div>


            <div>

            </div>

        </div>

    }
</div>

@section ContentTitle{
    <div class="title"><h1>@Localizer["MyTick"]</h1></div>
    <div class="buttons">
        <a class="card-button" href="~/Home/MyTickets?sort=0">
            <span class="nav-item">@Localizer["All"]</span>
        </a>
        <a class="card-button" href="~/Home/MyTickets?sort=1">
            <span class="nav-item">@Localizer["Selling"]</span>
        </a>
        <a class="card-button" href="~/Home/MyTickets?sort=2">
            <span class="nav-item">@Localizer["Waiting"]</span>
        </a>
        <a class="card-button" href="~/Home/MyTickets?sort=3">
            <span class="nav-item">@Localizer["Sold"]</span>
        </a>
    </div>
}