EPAM_TICKETO_TASK/EpamTicketoTask.EmptyTemplate/Models/ViewModels/Ticket/TicketEditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EpamTicketoTask.EmptyTemplate.Models.ViewModels.Ticket
{
    public class TicketEditViewModel
    {
        public string EventName { get; set; }
        public string Id { get; set; }
        public string EventId { get; set; }
        [Required]
        [Range(0.01,999999)]
        public decimal Price { get; set; }
        public string Notes { get; set; }
    }
}

EPAM_TICKETO_TASK/EpamTicketoTask.EmptyTemplate/Models/ViewModels/Ticket/TicketIndexViewModel.cs
using EpamTicketoTask.Data.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EpamTicketoTask.EmptyTemplate.Models.ViewModels.Ticket
{
    public class TicketIndexViewModel
    {
        public string Id { get; set; }
        public string EventId { get; set; }
        public string EventName { get; set; }
        public DateTime EventDate { get; set; }
        public decimal Price { get; set; }
        public string Notes { get; set; }
        public string SellerFullName { get; set; }
        public string SellerUserName { get; set; }
        public int OrderCount { get; set; }
        public bool IsSold { get; set; }
    }
}

EPAM_TICKETO_TASK/EpamTicketoTask.EmptyTemplate/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using EpamTicketoTask.BusinessLogic.Abstractions;
using EpamTicketoTask.BusinessLogic.Models.DTO;
using EpamTicketoTask.BusinessLogic.Infrastucture;
using AutoMapper;
using EpamTicketoTask.EmptyTemplate.Models.ViewModels.Ticket;
using EpamTicketoTask.EmptyTemplate.Models.ViewModels.Event;

namespace EpamTicketoTask.EmptyTemplate.Controllers
{
    public class TicketController : Controller
    {
        private IServiceStorage serviceStorage;

        public TicketController(IServiceStorage serviceStorage)
        {
            this.serviceStorage = serviceStorage;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Add(string eventId, string eventName)
        {
            TicketEditViewModel model = new TicketEditViewModel
            {
                EventId = eventId,
                EventName = eventName
            };
            return View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Add(TicketEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            //Немного магии от автомаппера... она точно производительнее?
            Mapper.Initialize(cfg => cfg.CreateMap<TicketEditViewModel, TicketDTO>()
            .ForMember("SellerUserName",opt=>opt.MapFrom(src=>User.Identity.Name)));
            TicketDTO ticketDto = Mapper.Map<TicketEditViewModel, TicketDTO>(model);

            serviceStorage.GetService<ITicketService>().Make(ticketDto);
            return Redirect("~/Home/MyTickets");
        }

        [HttpGet]
        [Authorize]
        public IActionResult Edit(string id)
        {
            TicketDTO ticketDto = serviceStorage.GetService<ITicketService>().Get(id);

            if (ticketDto.SellerUserName == User.Identity.Name)
                return Redirect("~/Home/MyTickets");

            Mapper.Initialize(cfg => cfg.CreateMap<TicketDTO, TicketEditViewModel>());
            TicketEditViewModel model = Mapper.Map<TicketDTO,TicketEditViewModel>(ticketDto);

            return View(model);
        }
        [HttpPost]
        [Authorize]
        public IActionResult Edit(TicketEditViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            Mapper.Initialize(cfg => cfg.CreateMap<TicketEditViewModel, TicketDTO>()
            .ForMember("SellerUserName", opt => opt.MapFrom(src => User.Identity.Name)));
            TicketDTO ticketDto = Mapper.Map<TicketEditViewModel, TicketDTO>(model);

            serviceStorage.GetService<ITicketService>().Update(ticketDto);
            return Redirect("~/Home/MyTickets");
        }

        [HttpGet]
        [Authorize]
        public IActionResult Delete(string Id)
        {
            TicketDTO dtoModel = serviceStorage.GetService<ITicketService>().Get(Id);

            Mapper.Initialize(cfg => cfg.CreateMap<TicketDTO, TicketIndexViewModel>());
            TicketIndexViewModel model = Mapper.Map<TicketDTO, TicketIndexViewModel>(dtoModel);
            return View(model);
        }
        [HttpPost]
        [Authorize]
        [ActionName("Delete")]
        public IActionResult DeleteConfirm(EventDisplayViewModel model)
        {
            try
            {
                serviceStorage.GetService<ITicketService>().Delete(model.Id);
            }
            catch (ValidationException e)
            {
                ModelState.AddModelError("ConEv", e.Message);
                return View(model);
            }
            return Redirect("~/Home/Index");
        }

    }
}

EPAM_TICKETO_TASK/EpamTicketoTask.EmptyTemplate/Views/Ticket/Add.cshtml
@model EpamTicketoTask.EmptyTemplate.Models.ViewModels.Ticket.TicketEditViewModel
@{
    ViewData["Title"] = "DeleteEvent";
}

<div class="card-list">
    <form method="post" asp-controller="Ticket" asp-action="Add">
        <div class="card ticket-card card-small">
            <div class="card-head">
                <h1>@Model.EventName</h1>
            </div>
            <hr />
            <div class="card-info">
                <label asp-for="Price"></label>
                <input asp-for="Price" />
                <span asp-validation-for="Price"></span>
                <div>
                    <label asp-for="Notes"></label><br />
                    <textarea asp-for="Notes" rows="5" res></textarea>
                    <span asp-validation-for="Notes"></span>
                </div>
            </div>

        </div>
        <div asp-validation-summary="All"></div>
        <div hidden="hidden">
            <input asp-for="EventId" />
            <input asp-for="EventName" />
        </div>
        <div>
            <input class="card-button red" type="submit" value="Продать" />
            <a class="card-button" href="~/Home/Index">Отмена</a>
        </div>
    </form>
</div>
@section ContentTitle{
    <div class="title">
        <h1>
            @Localizer["AddTicket"]
        </h1>
    </div>
}